back_homepage:
    path:     /
    defaults: { _controller: BackBundle:Main:index }


#
# Import annoncement routes
#
back_announcements:
    resource: "@BackBundle/Resources/config/routing/announcement.yml"
    prefix: /announcement

back_comments:
    resource: "@BackBundle/Resources/config/routing/comments.yml"
    prefix: /comments

