<?php

namespace PaP\BackBundle\Repository;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllByCriteria($order = "createdAt", $dir ="DESC")
    {


        $query = $this->createQueryBuilder("an")
            ->select( 'an.id','an.title','an.ref','an.price', 'an.photo')
            ->orderBy("an.{$order}", "{$dir}")
            ->getQuery();

        return $query->getResult();

    }

}
